#! /bin/bash

app/console assets:install
app/console assetic:dump
chmod -R 777 app/cache
app/console cache:clear
chmod -R 777 app/cache
app/console cache:clear --env=prod
chmod -R 777 app/cache
chmod -R 777 app/logs
top
