app:
    resource: '@AppBundle/Controller/'
    type: annotation

marvel_id:
    resource: "@MarvelLoginBundle/Resources/config/routing.yml"
    prefix:   /
dashboard_id:
    resource: "@MarvelCoreBundle/Resources/config/routing.yml"
    prefix:   /
